apiVersion: v1
kind: Namespace
metadata:
  name: infra-metallb
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  interval: 10m0s
  url:  https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra-metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: infra-metallb
      version: "0.13.7"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  ipAddressPools:
  - 192.168.100.20/32