apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  addresses:
  - 192.168.100.210/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  ipAddressPools:
  - metallb
