apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  addresses:
  - 192.168.100.210/32
  - 192.168.100.211/32
  - 192.168.100.212/32
  - 192.168.100.213/32
  - 192.168.100.214/32
  - 192.168.100.215/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb
  namespace: infra-metallb
spec:
  ipAddressPools:
  - metallb
