---
apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard
  namespace: adguard
spec:
  selector:
    matchLabels:
      app: adguard # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: adguard # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: adguard
        image: adguard/adguardhome:latest
        ports:
        - containerPort: 53
          protocol: TCP
          name: dns-tcp
        - containerPort: 53
          protocol: UDP
          name: dns-udp
        - containerPort: 80
          protocol: TCP
          name: http
        volumeMounts:
        - name: adguard-primary-conf
          mountPath: /opt/adguardhome/conf
        - name:
          mountPath: /opt/adguardhome/work
  volumeClaimTemplates:
  - metadata:
      name: conf
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "topolvm"
      resources:
        requests:
          storage: 100Mi
  - metadata:
      name: work
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "topolvm"
      resources:
        requests:
          storage: 100Mi