authentik:
    secret_key: M2NXMmNwRkFqdkxVaGM1cjY2I1V6QG5zdHp5diomZWdyU24lUWUlNXVaRyFWNnVRXlE=
    postgresql:
        password: N0pMdyo0TXhvNW5YQ0F5M25EN1JiS2JMbndNeHhyVDNUcWtvdUohUnNQQkszZCQkTEM=
postgresql:
    enabled: true
    password: N0pMdyo0TXhvNW5YQ0F5M25EN1JiS2JMbndNeHhyVDNUcWtvdUohUnNQQkszZCQkTEM=
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19q4q30qezma5jmfl5s2hv7xgws8z6030wlvj8mc6xjaenay2c48s42epnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRFRBRWFsaVZXSHlwNkhC
            VW5MVW9kQ0paN0oyWGlDUSsrem5tNU1GOW1ZCkUrRG15MUhvN2phQnhDZHhmYmtZ
            ZnY3TjF5MzJaaitDY21TTHB6Q1dtS2MKLS0tIDlJOUh5aWc5TjZTWEUrUU9xUk1R
            MDMwaVpWWE1DSjJ3SmNxUTdaM25KQm8KQvLiHiOG5QUtfnl/TEMer0xGjoVZgTEa
            QGU99SgK8+U5Lc+dyh310O47sQLajUoASriddyCFkevAIwlIIXXZyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T18:17:42Z"
    mac: ENC[AES256_GCM,data:1jQR54zm8nAOyY1ZFwEBR0+jy59cuufWXdpSZhOzl7z33P+1LZwYX1RsdoOCYOgHESSZQqZPvndRBgh6KLo0o0uGp9HmLsvONQjU+G+RHtf7WuO1PTzhmFGGxI1t8LWnd5FynYdbc0b/qRvzfcyNuohtsOaQ1/4e8DUo5D5bAc8=,iv:qYeBobA56HrGTBe37NWTipkNy31pkrEyDNqHNLOsL2w=,tag:oS6t6ocOJUl0JdwWgxiCng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
