apiVersion: v1
kind: Secret
metadata:
    name: helm-secrets
    namespace: app-authentik
type: Opaque
data:
    authentik:
        secret_key: ENC[AES256_GCM,data:Ogsl6L39XkIRrpELiBAfztjuL3TXL7V/II1jftMwlXitC2yJuBezNGLWqV+EpVYBaoAE9odXfq4zHw+rxFSlyWytuiA=,iv:miVjuhfufjZ0/OdN+Y5rMj4At9zY4voOHTVu6mmyYtM=,tag:MAb1kZ3LtZknmWn3QA52bg==,type:str]
        postgresql:
            password: ENC[AES256_GCM,data:f6U/cUv4NJE77ue47GmMFUBUwBTgrtHKr7JSgFdSe4QMdBY64X/D2wOHjTsw5hVMi9w6svv+Ryy6ESMatxDE+xdeAlI=,iv:Pg4+Xact+WsIjXEbtVvoUiUG/QpdzJRauL3leWUZK10=,tag:3hiT+bj1vi0dHjK+cRpYHA==,type:str]
    postgresql:
        password: ENC[AES256_GCM,data:Z+kcekAXcSAEPYpXgDs0DyS16ynjmv9LgA0W0u1oIrZhfzysEGIqnLXa0sqp3VNRYlsNGY4f4ZVoE03o0tt/vqCKu+g=,iv:ZexOEQC20ZSOuVft639ejTkKZHi3UOyOBeSP2jp9eEA=,tag:92BNKPuQp13rxRLpz7JUoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19q4q30qezma5jmfl5s2hv7xgws8z6030wlvj8mc6xjaenay2c48s42epnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRFRBRWFsaVZXSHlwNkhC
            VW5MVW9kQ0paN0oyWGlDUSsrem5tNU1GOW1ZCkUrRG15MUhvN2phQnhDZHhmYmtZ
            ZnY3TjF5MzJaaitDY21TTHB6Q1dtS2MKLS0tIDlJOUh5aWc5TjZTWEUrUU9xUk1R
            MDMwaVpWWE1DSjJ3SmNxUTdaM25KQm8KQvLiHiOG5QUtfnl/TEMer0xGjoVZgTEa
            QGU99SgK8+U5Lc+dyh310O47sQLajUoASriddyCFkevAIwlIIXXZyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-21T18:30:19Z"
    mac: ENC[AES256_GCM,data:FN6pGoqugFGzTr0LaLaVvqNtgLUKtCWEQEYYUZ0N5nXthaV5bTclyiI/E76srz7SlTT7pwzw5S28MgO9ZrCB8CG7bwYooRSgiJOjJ2yYn+RuoGwu6jxQXOPew9wdoh3bV10tf9ucDNXjKE/Lyq1qiTQ32VvpotRef43UkiGzCko=,iv:lTLhejMtkP6KcswJ56kIeCxirz3uOfP9XvhLXEcT3Sk=,tag:tDErJsWUxiYSg7eZ6xus+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
