apiVersion: v1
kind: Secret
metadata:
    name: helm-secrets
    namespace: ghost
type: Opaque
data:
    ghostEmail: ENC[AES256_GCM,data:9CXFcN44NKLQE1bNq99mhOubHcvD/y+M6y6d4wWEfaM=,iv:XHW/uhIVuU8OUSyg/+4j6Ox9lgdJG0JuzMNENmx47Jg=,tag:NpeCQmsw9b7qpSCwMpA8JQ==,type:str]
    ghostUsername: ENC[AES256_GCM,data:nJ3XpLUpSt/flAj19Pau2mzLtqw=,iv:8GNgeDPi+flkegn9DzjTS1M5tOh1WnW2GXPAB/UbIZg=,tag:YBgh67ImKpBYWnaLHf5aRw==,type:str]
    ghostPassword: ENC[AES256_GCM,data:NHNM/w2/0SxCB/riBNjZfRlT1FlCun+FbH1yEmJDY1B6kK3nDNi94w==,iv:g+3IAj5jzuzblcyUoOfSSaHBzDtijgXF92DI9U1yT+g=,tag:wdYkwdxxKG22A2/OY5mBYQ==,type:str]
    mysql:
        auth:
            rootPassword: ENC[AES256_GCM,data:uNUaj9ntBwHj6bQPeOiN6Np1wAiEYGWoWQaBps9l4BCIG1sX9gSQrA==,iv:NKKJ6fp4eLCptstmwhJohTAyLCHqpnCn2ugvgooIQyw=,tag:n1CHQSLBlRG0S8n3LP+OYA==,type:str]
            username: ENC[AES256_GCM,data:TiQuIhXU64U=,iv:uGVuiIUsLnEdhi1hICRM6YFVjRMjWwmKzHH+L4TsDkg=,tag:xNg5xnbt4FDwdcU9ca3kow==,type:str]
            password: ENC[AES256_GCM,data:u+dJZdDreVGxWwDuVLKWkbxbRmqjFE0iyG8LkZ48FwLcuQgyktP5yQ==,iv:mXThtTuF84AiUfRnYjfm0d+f0t6M+e052eLpOWHF4fc=,tag:NQA8UgwcCEu9z9ehu4zuyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19q4q30qezma5jmfl5s2hv7xgws8z6030wlvj8mc6xjaenay2c48s42epnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRFRBRWFsaVZXSHlwNkhC
            VW5MVW9kQ0paN0oyWGlDUSsrem5tNU1GOW1ZCkUrRG15MUhvN2phQnhDZHhmYmtZ
            ZnY3TjF5MzJaaitDY21TTHB6Q1dtS2MKLS0tIDlJOUh5aWc5TjZTWEUrUU9xUk1R
            MDMwaVpWWE1DSjJ3SmNxUTdaM25KQm8KQvLiHiOG5QUtfnl/TEMer0xGjoVZgTEa
            QGU99SgK8+U5Lc+dyh310O47sQLajUoASriddyCFkevAIwlIIXXZyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T18:46:50Z"
    mac: ENC[AES256_GCM,data:ZLT5FZiZs0lpvB3Jz5nCq7aIcYgzPqPcMCyLYxoIpbQL//5p6O4QNWm8eMpc/maj4+NfxcZ8TJeubNNrPYnRTtmfbdOzS/3BoQc4X9cGr7kaPrZo9ngv+dIF/XYuBqLnCM3zhi+aUb1niZ5tPAYL2rnQFMYs0VxteFGD8dEP+ys=,iv:1WKhrPfNxlKj1nQd52Hc9oGzkP4pZ9gM5TSg04DE0Eg=,tag:RUVozw2Hvvq6xIofagBzVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
