apiVersion: v1
kind: Secret
metadata:
    name: helm-secrets
    namespace: ghost
stringData:
    ghostEmail: ENC[AES256_GCM,data:6E5iEjUuJx30dtPwpXCjOT69OSBfdIo=,iv:dlNVx1bYQtACL+emiaywt5HzHeZ9C1yTMg3qfPno6dg=,tag:txluAotgQxVKM62z4E7HUQ==,type:str]
    ghostUsername: ENC[AES256_GCM,data:iHH/IAkMY45AaqswmA==,iv:oUZ8X8F2KynqxVRRh7j8GTp70O5i58PxtsPTbL1h1OM=,tag:WAFy5GV5cF8Z8Je4e/ucwQ==,type:str]
    ghostPassword: ENC[AES256_GCM,data:WYU0tYWvBp+R1Ao/9aZ9JMeyAVdkoj7W7BE2Xcku,iv:u+508CBuMkJUDlm1T8lcJSGPsqVTFIVmw2fDPQlyPkE=,tag:34UCrSHlphQGzN5bkFDV5A==,type:str]
    mysqlRootPassword: ENC[AES256_GCM,data:+d07GqFTHsLRGUEIkt3eaoavU6rEqNJGDZAO0r+4,iv:upwjOgV5in9vPL/h1Xqha62zixd1/wozaRqF5HBcAsY=,tag:rwSYWCe/1/VPXUIul5IHBQ==,type:str]
    mysqlUsername: ENC[AES256_GCM,data:W8CH+8E=,iv:WINkhq0tOWRxfTxNmuXduZYNoKNSHEORpAs7rp1fPO0=,tag:MPXcee6MzfynbKP79xkqcQ==,type:str]
    mysqlPassword: ENC[AES256_GCM,data:QIbf5cf1ez1ADFO3Pu+2U3iTf1dywUYEZ18Hs/fL,iv:kAa0RWBFRweE5VelXSn5GiQ4P++gFYPkyVahStg0Itw=,tag:i4qlxY/6POWDs56fW/3rkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19q4q30qezma5jmfl5s2hv7xgws8z6030wlvj8mc6xjaenay2c48s42epnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRFRBRWFsaVZXSHlwNkhC
            VW5MVW9kQ0paN0oyWGlDUSsrem5tNU1GOW1ZCkUrRG15MUhvN2phQnhDZHhmYmtZ
            ZnY3TjF5MzJaaitDY21TTHB6Q1dtS2MKLS0tIDlJOUh5aWc5TjZTWEUrUU9xUk1R
            MDMwaVpWWE1DSjJ3SmNxUTdaM25KQm8KQvLiHiOG5QUtfnl/TEMer0xGjoVZgTEa
            QGU99SgK8+U5Lc+dyh310O47sQLajUoASriddyCFkevAIwlIIXXZyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-05T19:29:52Z"
    mac: ENC[AES256_GCM,data:PtV4hxEyW7VHqZ1vPOZps4pcV/sazp4qVPilzd2mbpZ5Cyw3TgTNtNS1RHo8jomvKXVSDrVGGnJ3Oy+2g/FxozKmE649jqPcXMMIpgtaxF91Qx/892MtBl7z3uWI2CEOSwc0gdCql1V9tu6HzE05owFB/Ev52FFZDuc/DqXUSzU=,iv:KlcMQ4FQR6qoWIH2gx8CyFzPRLvGfNA2fSHD2dnNF2s=,tag:HED2A9CeFknkApIk93gblQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
