apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: ghost
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      hostname: ghost-stage.familie-siebert.de
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
        # see https://ghost.org/docs/faq/proxying-https-infinite-loops/
        traefik.ingress.kubernetes.io/router.middlewares: "ghost-blog-add-x-forwarded-proto@kubernetescrd"
      tls: false 
      extraTls:
        - hosts:
            - ghost-stage.familie-siebert.de
          secretName: ghost-stage-tls
      type: ClusterIP
      annotations: 
        traefik.ingress.kubernetes.io/service.serversscheme: http
    persistence:
      enabled: true
      storageClass: topolvm
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    ghostEnableHttps: true
    allowEmptyPassword: false
    extraEnvVars:
      - name: LOG_LEVEL
        value: DEBUG
  valuesFrom:
    - kind: Secret
      name: helm-secrets
      valuesKey: ghostUsername
      targetPath: ghostUsername
    - kind: Secret
      name: helm-secrets
      valuesKey: ghostPassword
      targetPath: ghostPassword
    - kind: Secret
      name: helm-secrets
      valuesKey: ghostEmail
      targetPath: ghostEmail 
    - kind: Secret
      name: helm-secrets
      valuesKey: mysqlRootPassword
      targetPath: mysql.auth.rootPassword 
    - kind: Secret
      name: helm-secrets
      valuesKey: mysqlUsername
      targetPath: mysql.auth.username
    - kind: Secret
      name: helm-secrets
      valuesKey: mysqlPassword
      targetPath: mysql.auth.password

