apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-kube-prometheus-stack
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-kube-prometheus-stack
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
---
#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: monitoring-kube-prometheus-stack
#spec:
#  releaseName: kube-prometheus-stack
#  chart:
#    spec:
#      chart: kube-prometheus-stack
#      sourceRef:
#        kind: HelmRepository
#        name: kube-prometheus-stack
#        namespace: monitoring-kube-prometheus-stack
#      version: "41.9.1"
#  values:
#    nameOverride: kps
#    fullnameOverride: kps
#    prometheus:
#      prometheusSpec:
#        storageSpec:
#          volumeClaimTemplate:
#            spec:
#              storageClassName: openebs-jiva-csi-default
#              accessModes: ["ReadWriteOnce"]
#              resources:
#                requests:
#                  storage: 5Gi
#            selector: {}
#
#  interval: 1h0m0s
#  install:
#    remediation:
#      retries: 3
