apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-kube-prometheus-stack
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-kube-prometheus-stack
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring-kube-prometheus-stack
      version: "41.9.1"
  values:
    nameOverride: kps
    fullnameOverride: kps
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        configReloaders: true
        general: true
        k8s: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: true
        kubeApiserverHistogram: true
        kubeApiserverSlos: true
        kubeControllerManager: true
        kubelet: true
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: true
        kubeSchedulerAlerting: true
        kubeSchedulerRecording: true
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
    grafana:
      ingress:
        enabled: true
        #ingressClassName: traefik
        annotations:
          kubernetes.io/ingress.class: traefik
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
        hosts:
          - grafana-stage.familie-siebert.de
        path: /
        tls:
         - secretName: grafana-general-tls
           hosts:
           - grafana-stage.familie-siebert.de
      #persistence:
      #  type: pvc
      #  enabled: true
      #  storageClassName: openebs-jiva-csi-default
      #  accessModes:
      #    - ReadWriteMany
      #  size: 1Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: openebs-jiva-csi-default
              accessModes: ["ReadWriteMany"]
              resources:
                requests:
                  storage: 5Gi
            selector: {}
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring-prometheus-adapter
spec:
  releaseName: prometheus-adapter
  chart:
    spec:
      chart: prometheus-adapter
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring-kube-prometheus-stack
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
