apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m0s
  url:  https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  releaseName: cilium
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
      version: "1.11.9"
  values:
    ipam:
      mode: kubernetes
    kubeProxyReplacement: strict
    k8sServiceHost: 192.168.100.200
    operator:
      replicas: 2
    hubble:
      relay:
        enabled: false
      ui:
        enabled: false
    k8sServicePort: 6443
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
