apiVersion: v1
kind: Namespace
metadata:
  name: infra-traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: infra-traefik
spec:
  interval: 10m0s
  url:  https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra-traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: infra-traefik
      version: "20.2.0 "
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 50%
    service:
      annotations: 
        external-dns.alpha.kubernetes.io/hostname: "*.stage.familie-siebert.de"
