apiVersion: v1
kind: Namespace
metadata:
  name: infra-openebs-jiva
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs-jiva
  namespace: infra-openebs-jiva
spec:
  interval: 10m0s
  url:  https://openebs.github.io/jiva-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infra-openebs-jiva
  namespace: infra-openebs-jiva
spec:
  releaseName: openebs-jiva
  chart:
    spec:
      chart: jiva
      sourceRef:
        kind: HelmRepository
        name: openebs-jiva
        namespace: infra-openebs-jiva
      version: "3.3.0"
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: apps/v1
            kind: DaemonSet
            metadata:
              name: openebs-jiva-csi-node
            spec:
              template:
                spec:
                  hostPID: true
    - kustomize:
        patchesStrategicMerge:
            - apiVersion: v1
              kind: ConfigMap
              metadata:
                name: openebs-jiva-csi-iscsiadm
              data:
                iscsiadm: |
                  #!/bin/sh
                  iscsid_pid=$(pgrep iscsid)
                  nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
