apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: ghost
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      hostname: ghost-stage.familie-siebert.de
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
      tls:
      - secretName: ghost-general-tls
        hosts:
        - ghost-stage.familie-siebert.de
    persistence:
      enabled: true
      storageClass: topolvm
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    ghostUsername: admin
    ghostPassword: password12345
    mysql:
      auth:
        rootPassword: password12345
  