apiVersion: v1
kind: Namespace
metadata:
  name: ghost
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghost
  namespace: ghost
spec:
  interval: 1h0m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: ghost
spec:
  chart:
    spec:
      chart: ghost
      sourceRef:
        kind: HelmRepository
        name: ghost
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      hostname: ghost-stage.familie-siebert.de
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-familie-siebert-de
      tls: true
    service:
      type: ClusterIP  
    persistence:
      enabled: true
      storageClass: topolvm
      size: 5Gi
      accessModes:
        - ReadWriteOnce
    #ghostEnableHttps: true
    ghostUsername: ghost@markussiebert.com
    ghostPassword: 7m@WKiNyJArs8aL*UzhZ4dz!wrHF!1
    allowEmptyPassword: false
    extraEnvVars:
      - name: LOG_LEVEL
        value: DEBUG
    mysql:
      auth:
        rootPassword: 7m@WKiNyJArs8aL*UzhZ4dz!wrHF!2
        username: ghost
        password: 7m@WKiNyJArs8aL*UzhZ4dz!wrHF!3
  