apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: openebs-jiva-csi-iscsiadm
  namespace: infra-openebs-jiva
data:
  iscsiadm: |
    #!/bin/sh
    iscsid_pid=$(pgrep iscsid)

    nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: openebs-jiva-csi-node-daemonset-patch
  namespace: infra-openebs-jiva
spec:
  # ...omitted for brevity
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/hostPID
          value: true
      target:
          kind: Deployment
          name: openebs-jiva-csi-node
          namespace: infra-openebs-jiva