apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: openebs-jiva-csi-iscsiadm
  namespace: infra-openebs-jiva
data:
  iscsiadm: |
    #!/bin/sh
    iscsid_pid=$(pgrep iscsid)

    nsenter --mount="/proc/${iscsid_pid}/ns/mnt" --net="/proc/${iscsid_pid}/ns/net" -- /usr/local/sbin/iscsiadm "$@"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels: {}
  name: openebs-jiva-csi-node
  namespace: infra-openebs-jiva
spec:
  template:
    spec:
      containers: []
      hostPID: true