apiVersion: v1
kind: Namespace
metadata:
  name: infra-authelia
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: authelia
  namespace: infra-authelia
spec:
  interval: 10m0s
  url: https://charts.authelia.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: infra-authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: infra-authelia
      version: "0.8.48"
  # see https://github.com/authelia/chartrepo/blob/master/charts/authelia/values.yaml
  # values:
  interval: 1h0m0s
  install:
    remediation:
      retries: 3

